---
- name: Restore BeeGFS filesystem
  hosts: all
  any_errors_fatal: true
  become: yes
  roles:
    - role: beegfs_server
      vars:
        beegfs_state: "present"
        beegfs_format_disks: false