---
- import_tasks: repo.yaml
  when: beegfs_install_repo

- import_tasks: wipe.yaml
  when: beegfs_format_disks|bool and beegfs_state == "present"

- import_tasks: format.yaml
  when: beegfs_format_disks|bool and beegfs_state == "present"

- import_tasks: start_mgmtd.yaml
  when: beegfs_state == "present" and ansible_hostname == mgsnode

- import_tasks: start_meta.yaml
  when: beegfs_state == "present"

- import_tasks: start_storage.yaml
  when: beegfs_state == "present"

- import_tasks: stop_all.yaml
  when: beegfs_state == "absent"

- import_tasks: wipe.yaml
  when: beegfs_state == "absent"