---
- name: enable beegfs  repo
  yum_repository:
    name: BeeGFS7
    description: "BeeGFS 7"
    file: beegfs-repo
    baseurl: "{{ beegfs_repo_url }}"
    gpgcheck: no

- name: install beegfs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libibverbs-utils
    - beegfs-mgmtd
    - beegfs-meta
    - beegfs-storage
    - beegfs-client
    - beegfs-helperd
    - beegfs-utils
    - beegfs-admon