---
- name: create meta service
  block:
    - name: create metadata config dirs
      file:
        path: "/etc/beegfs/{{ item }}.d/"
        state: directory
      loop: "{{ metadata.values() }}"

    - name: add template metadata conf
      command: "cp /etc/beegfs/beegfs-meta.conf /etc/beegfs/{{ item }}.d/beegfs-meta.conf"
      args:
        creates: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
      loop: "{{ metadata.values() }}"

    - name: make metadata dir
      file:
        path: "/data/{{ fs_name }}/{{ item }}/metadata"
        state: directory
      loop: "{{ metadata.values() }}"

    # TODO: fix up mgsnode bit here! and port below

    - name: setup metadata
      command: |
          /opt/beegfs/sbin/beegfs-setup-meta \
          -p /data/{{ fs_name }}/{{ item.value }}/metadata \
          -s {{ item.key|int + 1 }} \
          -m {{ mgsnode }}
          -c /etc/beegfs/{{ item.value }}.d/beegfs-meta.conf
          -S {{ fs_name }}-{{ ansible_host }}-metadata-{{ item.key }}-{{ item.value }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"
      with_dict: "{{ metadata }}"

    - name: set TCP meta port
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^connMetaPortTCP.*'
        line: "connMetaPortTCP = {{ port_start_meta + port_step*port_multiple[item] }}"
      loop: "{{ metadata.values() }}"
    - name: set UDP meta port
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^connMetaPortUDP.*'
        line: "connMetaPortUDP = {{ port_start_meta + port_step*port_multiple[item] }}"
      loop: "{{ metadata.values() }}"

    - name: set mgmtd port for meta
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^connMgmtdPortTCP.*'
        line: "connMgmtdPortTCP = {{ port_start_mgmtd }}"
      loop: "{{ metadata.values() }}"
    - name: set mgmtd port for meta
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^connMgmtdPortUDP.*'
        line: "connMgmtdPortUDP = {{ port_start_mgmtd }}"
      loop: "{{ metadata.values() }}"

    - name: set metadata log
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^logStdFile.*'
        line: "logStdFile = /var/log/beegfs-metadata-{{ fs_name }}-{{ item }}.log"
      loop: "{{ metadata.values() }}"

    - name: write out interfaces file
      copy:
        content: "{{ interfaces[item] }}"
        dest: "/etc/beegfs/{{ item }}.d/connInterfacesFile"
      loop: "{{ metadata.values() }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: '^connInterfacesFile.*'
        line: "connInterfacesFile = /etc/beegfs/{{ item }}.d/connInterfacesFile"
      loop: "{{ metadata.values() }}"

    - name: Set appropriate tuneBindToNumaZone
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
        regexp: "^tuneBindToNumaZone.*"
        line: "tuneBindToNumaZone={{ numa[item] }}"
      loop: "{{ metadata.values() }}"

    - name: Start services meta
      systemd:
        state: started
        name: "beegfs-meta@{{ item }}.service"
      loop: "{{ metadata.values() }}"

  when:
    - metadata|length > 0
