---
- name: create meta service
  block:
    - name: create metadata config dirs
      file:
        path: "/etc/beegfs/{{ item }}.d/"
        state: directory
      loop: "{{ metadata.values() }}"

    - name: add template metadata conf
      command: "cp /etc/beegfs/beegfs-meta.conf /etc/beegfs/{{ item }}.d/beegfs-meta.conf"
      args:
        creates: "/etc/beegfs/{{ item }}.d/beegfs-meta.conf"
      loop: "{{ storage.values() }}"

    - name: make metadata dir
      file:
        path: "/data/{{ fs_name }}/{{ item }}/metadata"
        state: directory
      loop: "{{ storage.values() }}"

    # TODO: fix up mgsnode bit here! and port below

    - name: setup metadata
      command: |
          /opt/beegfs/sbin/beegfs-setup-storage \
          -p /data/{{ fs_name }}/{{ item.value }}/metadata -r \
          -s {{ item.key }} \
          -m {{ mgsnode }}
          -c /etc/beegfs/{{ item.value }}.d/beegfs-meta.conf
          -S {{ fs_name }}-{{ ansible_host }}-metadata-{{ item.key }}-{{ item.value }}
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage target directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"
      with_dict: "{{ metadata }}"

    - name: set TCP storage port
      lineinfile:
        path: "/etc/beegfs/{{ item }}.d/beegfs-metdata.conf"
        regexp: '^connMetaPortTCP.*'
        line: "connStoragePortTCP = {{ port_start_meta + port_step*port_multiple[item] }}"
      loop: "{{ metadata.values() }}"

    - name: set meta port
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mdt_port }}"
      loop:
        - "connMetaPortTCP"
        - "connMetaPortUDP"

    - name: set mgmtd port for meta
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_port }}"
      loop:
        - "connMgmtdPortTCP"
        - "connMgmtdPortUDP"

    - name: set mgmtd logfile
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = /var/log/{{ fs_name }}-beegfs-meta.log"
      loop:
        - "logStdFile"

    - name: write out interfaces file
      copy:
        content: "{{ mdt_disk_info['if'] }}"
        dest: "{{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"
      loop:
        - "connInterfacesFile"

    - name: Start services meta
      systemd:
        state: started
        name: "beegfs-meta@{{ item }}.service"
      loop: "{{ metadata.values() }}"

  when:
    - metadata|length > 0
