---
- name: create meta service
  block:

    - name: Configure BeeGFS meta
      command: |
        /opt/beegfs/sbin/beegfs-setup-meta \
        -p {{ mdt_dir }} \
        -s {{ mdt_index }} \
        -m {{ mgs_ip }} \
        -S {{ fs_name }}-{{ ansible_host }}-{{ mdt }} \
        -c {{fs_config_dir}}beegfs-meta.conf
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"
      with_dict: metadata

    - name: set meta port
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mdt_port }}"
      loop:
        - "connMetaPortTCP"
        - "connMetaPortUDP"

    - name: set mgmtd port for meta
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_port }}"
      loop:
        - "connMgmtdPortTCP"
        - "connMgmtdPortUDP"

    - name: set mgmtd logfile
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = /var/log/{{ fs_name }}-beegfs-meta.log"
      loop:
        - "logStdFile"

    - name: write out interfaces file
      copy:
        content: "{{ mdt_disk_info['if'] }}"
        dest: "{{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-meta.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ fs_config_dir }}connInterfacesFile{{ mdt_disk_info['if'] }}"
      loop:
        - "connInterfacesFile"

    - name: Start services meta
      systemd:
        state: started
        name: "beegfs-meta@{{ fs_name }}.service"
  when:
    - metadata|length > 0
