---
# Note: this is only run when ansible_hostname == mgsnode
- set_fact:
    fs_config_dir: "/etc/beegfs/{{ fs_name }}.d/"
    mgmtd_port: "{{ port_start_mgmtd + port_host_multiple * port_step }}"
    mgs_disk: "{{ metadata[0] }}"
- set_fact:
    mgs_dir: "/data/{{ fs_name }}/{{ mgs_disk }}/mgs"
    mgs_interface: "{{ interfaces[mgs_disk] }}"
    mgs_port: "{{ port_start_mgmtd + port_step * port_multiple[mgs_disk] }}"
  when: mgs_disk is defined
- set_fact:
    mgs_ip: "{{ hostvars[mgsnode]['ansible_%s' | format(mgs_interface)]['ipv4']['address'] }}"
  when: mgs_disk is defined

- name: create template config
  block:
    - name: create fs config dir
      file:
        path: "{{ fs_config_dir }}"
        state: directory
    - name: copy default config
      shell: "cp /etc/beegfs/*.conf {{ fs_config_dir }}"
      args:
        creates: "{{ fs_config_dir }}beegfs-admon.conf"
  when: mgs_disk is defined

- name: create mgmtd service
  when: mgs_disk is defined
  block:
    - name: make mgs dir
      file:
        path: "{{ mgs_dir }}"
        state: directory

    # TODO: template out file instead?
    - name: BeeGFS mgmtd
      command: |
        /opt/beegfs/sbin/beegfs-setup-mgmtd \
        -p {{ mgs_dir }} -n \
        -S {{ fs_name }}-{{ ansible_host }}-{{ mgs_disk }} \
        -c {{fs_config_dir}}beegfs-mgmtd.conf
      register: command_result
      failed_when: "command_result.rc != 0 and ('ERROR: Storage directory is not empty.' not in command_result.stdout)"
      changed_when: "command_result.rc == 0"

    - name: set mgmtd port
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_port }}"
      loop:
        - "connMgmtdPortTCP"
        - "connMgmtdPortUDP"

    - name: set mgmtd ip
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ mgs_ip }}"
      loop:
        - "sysMgmtdHost"

    - name: set mgmtd logfile
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = /var/log/{{ fs_name }}-beegfs-mgmtd.log"
      loop:
        - "logStdFile"

    - name: write out interfaces file
      copy:
        content: "{{ mgs_interface }}"
        dest: "{{ fs_config_dir }}connInterfacesFile{{ mgs_interface }}"

    - name: set conInterfacesFile in config
      lineinfile:
        path: "{{ fs_config_dir }}beegfs-mgmtd.conf"
        regexp: '^{{ item }}.*'
        line: "{{ item }} = {{ fs_config_dir }}connInterfacesFile{{ mgs_interface }}"
      loop:
        - "connInterfacesFile"

    - name: Start mgmtd
      systemd:
        state: started
        name: "beegfs-mgmtd@{{ fs_name }}.service"
