---
# TODO: maybe call wipefs or ss out the block device headers

- name: Remove old Partition
  parted:
    device: "/dev/{{ item }}"
    number: 1
    state: absent
  loop: "{{ (metadata.values() + storage.values()) | unique }}"

- name: Wait for partition to disappear from /dev
  wait_for:
    path: "/dev/{{ item }}{{ partition_prefix }}1"
    state: absent
    timeout: 120
    sleep: 5
  loop: "{{ (metadata.values() + storage.values()) | unique }}"
