---
# TODO: maybe call wipefs or ss out the block device headers

- name: Remove old Partition
  parted:
    device: "/dev/{{ item }}"
    number: 1
    state: absent
  loop: "{{ (mdts.keys() + osts.keys()) | unique }}"

- name: Wait for partition to disappear from /dev
  wait_for:
    path: "/dev/{{ item }}p1"
    state: absent
    timeout: 120
    sleep: 5
  loop: "{{ (mdts.keys() + osts.keys()) | unique }}"